### ISSUE TITLE
Add additional topics to JSON

### ISSUE THREAD

**Issue by sebastianbeattie** [sebastianbeattie/the-best-academy-project-ever#4]
Add additional topics and more questions per topic to quiz JSON file

**Comment by GarwoD01** [comment]
User story – 1.1

A webpage that shows several quiz questions for a variety of different topics.

- History, Geography, Politics, Conservation, Celebrities, Law, Sport o 3 to 5 questions per topic.
- The topic list may be expanded if the website is fully developed.
